---
title: "Video Data"
output: html_document
---

Prep libraries and import datasheets
```{r}
library(tidyverse)

video_events <- read_csv("video Notable Events.csv")
video_morts <- read_csv("Mort Counts for Vid Analysis.csv")
no_event_vids <- read_csv("No Event Videos.csv")
video_times <- read_csv("Video Start and Stop Times.csv")
```


Joining event data sheet with start/stop time sheet and formatting go get real event times
```{r}
# this has several issues
# one it still thinks that my minutes are hours and seconds are minutes
# two, it's outputing the final time in seconds which isn't super helpful
# generated table is up in viewer tab above, look for other errors and address them
realtime_events <- video_events %>%
   left_join(video_times, by = "video_code")

realtime_events <- realtime_events %>%
  mutate(
    min = as.numeric(sub(":.*", "", timestamp)),
    sec = as.numeric(sub(".*:", "", timestamp)),
    video_seconds = min * 60 + sec,
    real_timestamp  = video_seconds * 29.97,
    event_true_time = start + real_timestamp
  )

```


### Bar Graphs ###
```{r}
#create bar chart showing notable events sans test times and feeds accross all cams
video_events %>%
  group_by(event_type, camera) %>%
  filter(event_type != "Test") %>%
  filter(event_type != "Feed") %>%
  summarize(count = n()) %>%
  ggplot(aes(x = event_type, y = count, fill = factor(camera))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Notable Events by Camera",
       x = "Event",
       y = "Count") +
  theme_minimal()

```

```{r}

#create bar chart showing notable events sans test by time of day
video_events %>%
group_by(event_type, time_of_day) %>%
  filter(event_type != "Test") %>%
  filter(event_type != "Feed") %>%
  summarize(count = n()) %>%
  ggplot(aes(x = event_type, y = count, fill = time_of_day)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Notable Events by Camera",
       x = "Event",
       y = "Count") +
  theme_minimal()


```

```{r}

#create bar chart total cannibalism morts by moult stage
video_events %>%
group_by(event_type, mort_moult_stage, time_of_day) %>%
  filter(mort_moult_stage != "NA") %>%
  filter(mort_cause == "Cannibalism") %>%
  summarize(count = n()) %>%
  ggplot(aes(x = mort_moult_stage, y = count, fill = time_of_day)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Cannibalism Events by Moult Stage",
       x = "Event",
       y = "Count") +
  theme_minimal()


```
Having the one 'moulting' bar is really ugly and hard to interpret, maybe should go back and re-watch, classify as either pre, post or unkown. I remeber that vid and it is weird


```{r}
# Moults over the full experiment
moult_tally <- video_events %>%
  filter(event_type == "Moult") %>%   
  group_by(day_number, camera, time_of_day) %>%
  summarise(count = n(), .groups = "drop")

ggplot(moult_tally, aes(x = day_number, y = count)) +
  geom_col(position = "dodge") +
  labs(
    title = "Moults by Day",
    x = "Day",
    y = "Moults",
    color = "Camera Number"
  ) +
  theme_minimal()
```

Fucking about with boxplots
```{r}

moult_count <- video_events %>%
  filter(event_type == "Moult") %>%
  group_by(camera, time_of_day) %>%
  summarize(count = n(), .groups = "drop")

ggplot(moult_count, aes(x = time_of_day , y = count, )) +
  geom_boxplot()

```